"""
Django settings for firstproject project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

import os
from pathlib import Path
from decouple import config
import dj_database_url
import cloudinary
import cloudinary.uploader
import cloudinary.api

# =========================
# BASE DIR
# =========================

BASE_DIR = Path(__file__).resolve().parent.parent


# =========================
# SECURITY
# =========================

SECRET_KEY = config(
    'SECRET_KEY',
    default='django-insecure-(-ehkytohn4q29k59h8=_ncqb)o(^_rkax!9!sjy#@^6*=ss-+'
)

RAZORPAY_KEY_ID="rzp_test_S479OjLDHxx5wH"
RAZORPAY_KEY_SECRET="Y6iC3HAclGLT4qUHgXtme5Bz"

DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = [
    '.vercel.app',
    'localhost',
    '127.0.0.1'
]


# =========================
# APPLICATIONS
# =========================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary_storage',
    'django.contrib.staticfiles',
    'cloudinary',

    # Your apps (unchanged)
    'product',
    'account',
]


# =========================
# MIDDLEWARE
# =========================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# =========================
# URL / WSGI
# =========================

ROOT_URLCONF = 'firstproject.urls'
WSGI_APPLICATION = 'firstproject.wsgi.application'


# =========================
# TEMPLATES
# =========================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'product.context_processors.categories_processor',
            ],
        },
    },
]


# =========================
# DATABASE
# =========================

DATABASES = {
    'default': dj_database_url.config(
        default=config('POSTGRES_URL', default='sqlite:///db.sqlite3'),
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# =========================
# PASSWORD VALIDATION
# =========================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# =========================
# I18N
# =========================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# =========================
# STATIC FILES
# =========================

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'static'
] if (BASE_DIR / 'static').exists() else []

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
WHITENOISE_USE_FINDERS = True


# =========================
# MEDIA (CLOUDINARY)
# =========================

cloudinary.config(
    cloud_name=config('CLOUDINARY_CLOUD_NAME', default='doa6q2xz2'),
    api_key=config('CLOUDINARY_API_KEY', default='191832161819549'),
    api_secret=config('CLOUDINARY_API_SECRET', default='Y6sMFk0H-qxp-cUqXagaBifd2-Y'),
    secure=True
)

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
MEDIA_URL = '/media/'


# =========================
# CSRF (VERCEL SAFE)
# =========================

CSRF_TRUSTED_ORIGINS = [
    'https://vercel.app',
]

VERCEL_URL = config('VERCEL_URL', default=None)
if VERCEL_URL:
    CSRF_TRUSTED_ORIGINS.append(f"https://{VERCEL_URL}")


# =========================
# DEFAULT FIELD
# =========================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
