# Generated by Django 5.2.7 on 2025-11-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='p_price',
            field=models.CharField(max_length=15),
        ),
    ]
