# Generated by Django 5.2.7 on 2025-11-14 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productdetails_p_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='p_image',
            field=models.ImageField(default='good', upload_to='images/'),
            preserve_default=False,
        ),
    ]
