# Generated by Django 5.2.7 on 2025-11-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productdetails_p_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('p_category', models.CharField(max_length=100)),
                ('p_description', models.TextField()),
                ('p_price', models.FloatField()),
                ('p_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='productDetails',
        ),
    ]
