# Generated by Django 5.2.7 on 2025-11-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_p_category_alter_product_p_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
