# Generated by Django 5.2.7 on 2026-01-21 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_rating_alter_product_rating_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating_count',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
